// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EC2Instance struct {
	ID        string  `json:"id"`
	Public    bool    `json:"public"`
	Name      string  `json:"name"`
	PublicIP  string  `json:"publicIP"`
	PrivateIP string  `json:"privateIP"`
	OsInfo    *OSInfo `json:"osInfo"`
}

type OSInfo struct {
	ID             string `json:"id"`
	Version        string `json:"version"`
	Arch           string `json:"arch"`
	PlatformDistro string `json:"platformDistro"`
	PlatformBase   string `json:"platformBase"`
}
