// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Ami struct {
	ID string `json:"id"`
}

type EC2Instance struct {
	ID               string  `json:"id"`
	Public           bool    `json:"public"`
	Name             string  `json:"name"`
	PublicIP         string  `json:"publicIP"`
	PrivateIP        string  `json:"privateIP"`
	AvailabilityZone string  `json:"availabilityZone"`
	OsInfo           *OSInfo `json:"osInfo"`
	Ami              *Ami    `json:"ami"`
}

type OSInfo struct {
	ID             string `json:"id"`
	Version        string `json:"version"`
	BuildVersion   string `json:"buildVersion"`
	Arch           string `json:"arch"`
	PlatformDistro string `json:"platformDistro"`
	PlatformBase   string `json:"platformBase"`
}
