// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Ami struct {
	ID string `json:"id"`
}

type ListeningApplication struct {
	ID      string `json:"id"`
	Address string `json:"address"`
	Port    string `json:"port"`
	Pid     string `json:"pid"`
}

type OSInfo struct {
	ID             string `json:"id"`
	Version        string `json:"version"`
	BuildVersion   string `json:"buildVersion"`
	Arch           string `json:"arch"`
	PlatformDistro string `json:"platformDistro"`
	PlatformBase   string `json:"platformBase"`
}

type OSPackage struct {
	ID         string `json:"id"`
	Version    string `json:"version"`
	Source     string `json:"source"`
	Size       string `json:"size"`
	Arch       string `json:"arch"`
	Revision   string `json:"revision"`
	Status     string `json:"status"`
	Maintainer string `json:"maintainer"`
	Section    string `json:"section"`
	Priority   string `json:"priority"`
}
